import Foundation

enum ImageCreationMode: String, CaseIterable, Identifiable {
    case generate = "Generate"
    case edit = "Edit"

    var id: String { rawValue }
}

enum ImageOutputSize: String, CaseIterable, Identifiable {
    case square = "1024x1024"
    case portrait = "1024x1536"
    case landscape = "1536x1024"

    var id: String { rawValue }

    var label: String {
        switch self {
        case .square: "Square"
        case .portrait: "Portrait"
        case .landscape: "Landscape"
        }
    }
}

enum ImageOutputQuality: String, CaseIterable, Identifiable {
    case low, medium, high
    var id: String { rawValue }
}

enum OpenAIImageError: LocalizedError {
    case missingCredentials
    case missingSource
    case invalidResponse
    case http(Int, String)

    var errorDescription: String? {
        switch self {
        case .missingCredentials:
            "Connect OpenAI or add an OpenAI API key in Settings first."
        case .missingSource:
            "Choose a source image to edit."
        case .invalidResponse:
            "OpenAI returned an image response Website Commander could not read."
        case .http(let status, let detail):
            "OpenAI image request failed (\(status)): \(detail)"
        }
    }
}

/// A focused client for one-shot website asset creation. Generated bytes are
/// returned to the chat composer and remain local until the user sends them and
/// explicitly approves the agent's staged repository change.
enum OpenAIImageService {
    static func create(
        mode: ImageCreationMode,
        prompt: String,
        size: ImageOutputSize,
        quality: ImageOutputQuality,
        source: Attachment?
    ) async throws -> Data {
        guard let auth = await ProviderCredentials.resolve("openai") else {
            throw OpenAIImageError.missingCredentials
        }

        let request: URLRequest
        switch mode {
        case .generate:
            request = try generationRequest(
                token: auth.token,
                prompt: prompt,
                size: size,
                quality: quality
            )
        case .edit:
            guard let source else { throw OpenAIImageError.missingSource }
            request = editRequest(
                token: auth.token,
                prompt: prompt,
                size: size,
                quality: quality,
                source: source
            )
        }

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw OpenAIImageError.invalidResponse
        }
        guard (200..<300).contains(http.statusCode) else {
            let detail = String((String(data: data, encoding: .utf8) ?? "Unknown error").prefix(500))
            throw OpenAIImageError.http(http.statusCode, detail)
        }
        guard
            let object = try JSONSerialization.jsonObject(with: data) as? [String: Any],
            let first = (object["data"] as? [[String: Any]])?.first,
            let encoded = first["b64_json"] as? String,
            let imageData = Data(base64Encoded: encoded)
        else {
            throw OpenAIImageError.invalidResponse
        }
        return imageData
    }

    private static func generationRequest(
        token: String,
        prompt: String,
        size: ImageOutputSize,
        quality: ImageOutputQuality
    ) throws -> URLRequest {
        var request = URLRequest(url: SiteAgentURL.constant("https://api.openai.com/v1/images/generations"))
        request.httpMethod = "POST"
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 300
        request.httpBody = try JSONSerialization.data(withJSONObject: [
            "model": "gpt-image-2",
            "prompt": prompt,
            "size": size.rawValue,
            "quality": quality.rawValue,
            "output_format": "png",
            "n": 1,
        ])
        return request
    }

    private static func editRequest(
        token: String,
        prompt: String,
        size: ImageOutputSize,
        quality: ImageOutputQuality,
        source: Attachment
    ) -> URLRequest {
        let boundary = "WebsiteCommander-\(UUID().uuidString)"
        var request = URLRequest(url: SiteAgentURL.constant("https://api.openai.com/v1/images/edits"))
        request.httpMethod = "POST"
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        request.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 300

        var body = Data()
        body.appendFormField("model", value: "gpt-image-1.5", boundary: boundary)
        body.appendFormField("prompt", value: prompt, boundary: boundary)
        body.appendFormField("size", value: size.rawValue, boundary: boundary)
        body.appendFormField("quality", value: quality.rawValue, boundary: boundary)
        body.appendFormField("output_format", value: "png", boundary: boundary)
        body.appendFormFile(
            "image[]",
            filename: source.filename,
            mimeType: source.mimeType,
            data: source.data,
            boundary: boundary
        )
        body.append(Data("--\(boundary)--\r\n".utf8))
        request.httpBody = body
        return request
    }
}

private extension Data {
    mutating func appendFormField(_ name: String, value: String, boundary: String) {
        append(Data("--\(boundary)\r\n".utf8))
        append(Data("Content-Disposition: form-data; name=\"\(name)\"\r\n\r\n".utf8))
        append(Data("\(value)\r\n".utf8))
    }

    mutating func appendFormFile(
        _ name: String,
        filename: String,
        mimeType: String,
        data: Data,
        boundary: String
    ) {
        let safeFilename = filename.replacingOccurrences(of: "\"", with: "_")
        append(Data("--\(boundary)\r\n".utf8))
        append(
            Data("Content-Disposition: form-data; name=\"\(name)\"; filename=\"\(safeFilename)\"\r\n".utf8)
        )
        append(Data("Content-Type: \(mimeType)\r\n\r\n".utf8))
        append(data)
        append(Data("\r\n".utf8))
    }
}
